apiVersion: apps/v1
kind: Deployment
metadata:
  name: access-verifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: access-verifier
  template:
    metadata:
      labels:
        app: access-verifier
    spec:
      containers:
      - name: access-verifier
        image: access-verifier:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
