apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-verifier-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: access-verifier
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: client-data-manager
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0